### ISSUE TITLE
AWS IoT Ouput Connector Instructions

### ISSUE THREAD

**Issue by Erodenberg** [Esri/aws-for-geoevent#1]
Hanoch,  
1. the link to the tutorial is broken.  It is currently going here and looks like it hasn't be posted yet. 
 http://www.arcgis.com/home/item.html?id=TBD 

2. Should I be able to find compiled transport and adapter JAR files or are you telling me I have to install Maven and compile them myself.  I'm not clear on what needs to be done from reading the documentation.

Is there another place to go for a finished connector?

**Comment by hanoch** [comment]
@Erodenberg as with other ArcGIS GeoEvent Server sample repos, this repo holds the source code, so you will need to build it in order to use it.
Some of those repos will also have a GeoEvent Server Gallery item, but as you can figure out from the link (includes `TBD`), a gallery item is not available yet.
